# Generated by Django 4.1.2 on 2022-10-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="siteinfo",
            options={
                "verbose_name": "Site Information",
                "verbose_name_plural": "Site Information",
            },
        ),
    ]
